---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        files: \.sh$
  - repo: local
    hooks:
      - id: packer-fmt
        name: packer fmt
        entry: packer fmt -check -diff
        language: system
        files: \.pkr\.hcl$
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.7.3
    hooks:
      - id: betterleaks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: markdown-table-formatter
        name: markdown-table-formatter
        entry: npx markdown-table-formatter
        language: node
        types: [markdown]
        additional_dependencies: ["markdown-table-formatter@1.6.1"]
